### ISSUE TITLE
请教是否有金旭亮老师的java的课件

### ISSUE THREAD

**Issue by aha-weikai** [fan2goa1/BIT-CS-UnderGraduate#3]
同学，请问你有金旭亮老师的java课件吗？我目前在b站看金旭亮老师的 2022年下半年我在北京理工大学计算机学院针对本院二年级学生开设"Java语言程序设计“专业选修课 这个课程，但是没有ppt，想请问一下，你是否有这个课件。谢谢。

**Comment by fan2goa1** [comment]
不好意思同学，我没有选金老师的课程，所以没有这个课件。

**Comment by aha-weikai** [comment]
> 不好意思同学，我没有选金老师的课程，所以没有这个课件。

谢谢回复
